In [84]:
import pandas as pd
import numpy as np

In [85]:
#input data
data=pd.read_csv('data_covid.csv')
data

id_kel nama_provinsi           nama_kota       nama_kecamatan  \
0    3173011001   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
1    3173011006   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
2    3173011002   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
3    3173011005   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
4    3173011004   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
..          ...           ...                 ...                  ...   
262  3101021002   DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU SELATAN   
263  3101021001   DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU SELATAN   
264  3101011003   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   
265  3101011002   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   
266  3101011001   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   

         nama_kelurahan  odp  proses_pemantauan  selesai_pemantauan  pdp  \
0      CENGKARENG BARAT    4                  1                   3    0   
1      CENGKARENG TIMUR    9                  3                   6    3   
2          DURI KOSAMBI    4                  0                   4    2   
3                 KAPUK    4                  3                   1    1   
4    KEDAUNG KALI ANGKE    2                  0                   2    0   
..                  ...  ...                ...                 ...  ...   
262           P. TIDUNG    0                  0                   0    0   
263         UNTUNG JAWA    0                  0                   0    0   
264          P. HARAPAN    0                  0                   0    0   
265           P. KELAPA    0                  0                   0    0   
266         P. PANGGANG    0                  0                   0    0   

     masih_dirawat  pulang_dan_sehat  positif  dirawat  sembuh  meninggal  \
0                0                 0        0        0       0          0   
1                3                 0        3        3       0          0   
2                1                 1        2        2       0          0   
3                0                 1        1        0       0          1   
4                0                 0        0        0       0          0   
..             ...               ...      ...      ...     ...        ...   
262              0                 0        0        0       0          0   
263              0                 0        0        0       0          0   
264              0                 0        0        0       0          0   
265              0                 0        0        0       0          0   
266              0                 0        0        0       0          0   

     self_isolation keterangan  
0                 0         no  
1                 0        yes  
2                 0        yes  
3                 0        yes  
4                 0         no  
..              ...        ...  
262               0         no  
263               0         no  
264               0         no  
265               0         no  
266               0         no  

[267 rows x 17 columns]

In [86]:
#lihat info data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   id_kel              267 non-null    int64 
 1   nama_provinsi       267 non-null    object
 2   nama_kota           267 non-null    object
 3   nama_kecamatan      267 non-null    object
 4   nama_kelurahan      267 non-null    object
 5   odp                 267 non-null    int64 
 6   proses_pemantauan   267 non-null    int64 
 7   selesai_pemantauan  267 non-null    int64 
 8   pdp                 267 non-null    int64 
 9   masih_dirawat       267 non-null    int64 
 10  pulang_dan_sehat    267 non-null    int64 
 11  positif             267 non-null    int64 
 12  dirawat             267 non-null    int64 
 13  sembuh              267 non-null    int64 
 14  meninggal           267 non-null    int64 
 15  self_isolation      267 non-null    int64 
 16  keterangan          267 no

In [87]:
#lihat data kosong
data.empty

False

In [88]:
#lihat ukuran data
data.size

4539

In [89]:
#tentukan index data
data.set_index('id_kel')

nama_provinsi           nama_kota       nama_kecamatan  \
id_kel                                                              
3173011001   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
3173011006   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
3173011002   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
3173011005   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
3173011004   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
...                  ...                 ...                  ...   
3101021002   DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU SELATAN   
3101021001   DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU SELATAN   
3101011003   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   
3101011002   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   
3101011001   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   

                nama_kelurahan  odp  proses_pemantauan  selesai_pemantauan  \
id_kel                                                                       
3173011001    CENGKARENG BARAT    4                  1                   3   
3173011006    CENGKARENG TIMUR    9                  3                   6   
3173011002        DURI KOSAMBI    4                  0                   4   
3173011005               KAPUK    4                  3                   1   
3173011004  KEDAUNG KALI ANGKE    2                  0                   2   
...                        ...  ...                ...                 ...   
3101021002           P. TIDUNG    0                  0                   0   
3101021001         UNTUNG JAWA    0                  0                   0   
3101011003          P. HARAPAN    0                  0                   0   
3101011002           P. KELAPA    0                  0                   0   
3101011001         P. PANGGANG    0                  0                   0   

            pdp  masih_dirawat  pulang_dan_sehat  positif  dirawat  sembuh  \
id_kel                                                                       
3173011001    0              0                 0        0        0       0   
3173011006    3              3                 0        3        3       0   
3173011002    2              1                 1        2        2       0   
3173011005    1              0                 1        1        0       0   
3173011004    0              0                 0        0        0       0   
...         ...            ...               ...      ...      ...     ...   
3101021002    0              0                 0        0        0       0   
3101021001    0              0                 0        0        0       0   
3101011003    0              0                 0        0        0       0   
3101011002    0              0                 0        0        0       0   
3101011001    0              0                 0        0        0       0   

            meninggal  self_isolation keterangan  
id_kel                                            
3173011001          0               0         no  
3173011006          0               0        yes  
3173011002          0               0        yes  
3173011005          1               0        yes  
3173011004          0               0         no  
...               ...             ...        ...  
3101021002          0               0         no  
3101021001          0               0         no  
3101011003          0               0         no  
3101011002          0               0         no  
3101011001          0               0         no  

[267 rows x 16 columns]

In [95]:
# Import LabelEncoder
from sklearn.preprocessing import LabelEncoder

# Creating labelEncoder
le = LabelEncoder()

# Converting string labels into numbers.
data['keterangan']=le.fit_transform(data['keterangan'])
data

id_kel nama_provinsi           nama_kota       nama_kecamatan  \
0    3173011001   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
1    3173011006   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
2    3173011002   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
3    3173011005   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
4    3173011004   DKI JAKARTA       JAKARTA BARAT           CENGKARENG   
..          ...           ...                 ...                  ...   
262  3101021002   DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU SELATAN   
263  3101021001   DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU SELATAN   
264  3101011003   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   
265  3101011002   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   
266  3101011001   DKI JAKARTA  KAB.ADM.KEP.SERIBU    KEP. SERIBU UTARA   

         nama_kelurahan  odp  proses_pemantauan  selesai_pemantauan  pdp  \
0      CENGKARENG BARAT    4                  1                   3    0   
1      CENGKARENG TIMUR    9                  3                   6    3   
2          DURI KOSAMBI    4                  0                   4    2   
3                 KAPUK    4                  3                   1    1   
4    KEDAUNG KALI ANGKE    2                  0                   2    0   
..                  ...  ...                ...                 ...  ...   
262           P. TIDUNG    0                  0                   0    0   
263         UNTUNG JAWA    0                  0                   0    0   
264          P. HARAPAN    0                  0                   0    0   
265           P. KELAPA    0                  0                   0    0   
266         P. PANGGANG    0                  0                   0    0   

     masih_dirawat  pulang_dan_sehat  positif  dirawat  sembuh  meninggal  \
0                0                 0        0        0       0          0   
1                3                 0        3        3       0          0   
2                1                 1        2        2       0          0   
3                0                 1        1        0       0          1   
4                0                 0        0        0       0          0   
..             ...               ...      ...      ...     ...        ...   
262              0                 0        0        0       0          0   
263              0                 0        0        0       0          0   
264              0                 0        0        0       0          0   
265              0                 0        0        0       0          0   
266              0                 0        0        0       0          0   

     self_isolation  keterangan  
0                 0           0  
1                 0           1  
2                 0           1  
3                 0           1  
4                 0           0  
..              ...         ...  
262               0           0  
263               0           0  
264               0           0  
265               0           0  
266               0           0  

[267 rows x 17 columns]

In [98]:
#variabel independent
x = data[['pulang_dan_sehat','positif','dirawat','sembuh','meninggal']]
x

#variabel dependent
y = data["keterangan"]
y

0      0
1      1
2      1
3      1
4      0
      ..
262    0
263    0
264    0
265    0
266    0
Name: keterangan, Length: 267, dtype: int64

In [99]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

from sklearn.naive_bayes import GaussianNB
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive Bayes
modelnb = GaussianNB()
# Memasukkan data training pada fungsi klasifikasi Naive Bayes
nbtrain = modelnb.fit(x_train, y_train)

In [100]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [101]:
np.array(y_test)

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [102]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.68423991e-18],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.68423991e-18],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.68423991e-18],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.68423991e-18],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.68423991e-18],
       [1.00000000e+00, 1.69521111e-16],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.68423991e-18],
       [0.00000000e+00, 1.00000000e+00],
       [1.000000

In [103]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[26,  0],
       [ 0, 28]], dtype=int64)

In [104]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        26
           1       1.00      1.00      1.00        28

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

