In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
cryotherapy = pd.read_excel("Cryotherapy.xlsx")
cryotherapy.head()

sex  age   Time  Number_of_Warts  Type  Area  Result_of_Treatment
0    1   35  12.00                5     1   100                    0
1    1   29   7.00                5     1    96                    1
2    1   50   8.00                1     3   132                    0
3    1   32  11.75                7     3   750                    0
4    1   67   9.25                1     1    42                    0

In [4]:
cryotherapy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   sex                  90 non-null     int64  
 1   age                  90 non-null     int64  
 2   Time                 90 non-null     float64
 3   Number_of_Warts      90 non-null     int64  
 4   Type                 90 non-null     int64  
 5   Area                 90 non-null     int64  
 6   Result_of_Treatment  90 non-null     int64  
dtypes: float64(1), int64(6)
memory usage: 5.0 KB


In [5]:
# variabel independen
x = cryotherapy.drop(["Result_of_Treatment"], axis = 1)
x.head()

sex  age   Time  Number_of_Warts  Type  Area
0    1   35  12.00                5     1   100
1    1   29   7.00                5     1    96
2    1   50   8.00                1     3   132
3    1   32  11.75                7     3   750
4    1   67   9.25                1     1    42

In [6]:
# variabel dependen
y = cryotherapy["Result_of_Treatment"]
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Result_of_Treatment, dtype: int64

In [8]:
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size = 0.2, random_state = 123)

In [9]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [12]:
klasifikasi = KNeighborsClassifier(n_neighbors = 5)

In [13]:
klasifikasi.fit(x_train, y_train)

KNeighborsClassifier()

In [14]:
y_pred = klasifikasi.predict(x_test)
y_pred

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1], dtype=int64)

In [15]:
klasifikasi.predict_proba(x_test)

array([[0.2, 0.8],
       [0.8, 0.2],
       [0.4, 0.6],
       [0.8, 0.2],
       [0. , 1. ],
       [0.8, 0.2],
       [0. , 1. ],
       [0.8, 0.2],
       [0. , 1. ],
       [0.6, 0.4],
       [1. , 0. ],
       [0.6, 0.4],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ],
       [0.8, 0.2],
       [1. , 0. ],
       [0.2, 0.8]])

In [17]:
print (confusion_matrix(y_test, y_pred))

[[8 1]
 [2 7]]


In [18]:
print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84         9
           1       0.88      0.78      0.82         9

    accuracy                           0.83        18
   macro avg       0.84      0.83      0.83        18
weighted avg       0.84      0.83      0.83        18



In [20]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8333333333333334